"""test

Revision ID: 9808e6e85b30
Revises: 
Create Date: 2026-03-06 10:08:02.257080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9808e6e85b30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_info_id'), 'student_info', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('sem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('pfp_url', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_table('co_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ia', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('sem', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_templates_id'), 'co_templates', ['id'], unique=False)
    op.create_table('co_question_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_no', sa.String(), nullable=False),
    sa.Column('co_no', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['co_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_question_mappings_id'), 'co_question_mappings', ['id'], unique=False)
    op.create_table('co_student_answer_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_no', sa.String(), nullable=False),
    sa.Column('mark', sa.String(), nullable=False),
    sa.Column('regno', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('ia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['co_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_student_answer_marks_id'), 'co_student_answer_marks', ['id'], unique=False)
    op.create_table('evaluation_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['co_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_schemas_id'), 'evaluation_schemas', ['id'], unique=False)
    op.create_table('student_evaluation_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_reg_no', sa.String(), nullable=False),
    sa.Column('upload_method', sa.String(), nullable=False),
    sa.Column('student_pdf_path', sa.String(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['evaluation_schemas.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_evaluation_progress_id'), 'student_evaluation_progress', ['id'], unique=False)
    op.create_table('student_answer_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_reg_no', sa.String(), nullable=True),
    sa.Column('question_no', sa.String(), nullable=False),
    sa.Column('mark_score', sa.Float(), nullable=False),
    sa.Column('total_mark', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['student_evaluation_progress.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_answer_evaluations_id'), 'student_answer_evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_answer_evaluations_id'), table_name='student_answer_evaluations')
    op.drop_table('student_answer_evaluations')
    op.drop_index(op.f('ix_student_evaluation_progress_id'), table_name='student_evaluation_progress')
    op.drop_table('student_evaluation_progress')
    op.drop_index(op.f('ix_evaluation_schemas_id'), table_name='evaluation_schemas')
    op.drop_table('evaluation_schemas')
    op.drop_index(op.f('ix_co_student_answer_marks_id'), table_name='co_student_answer_marks')
    op.drop_table('co_student_answer_marks')
    op.drop_index(op.f('ix_co_question_mappings_id'), table_name='co_question_mappings')
    op.drop_table('co_question_mappings')
    op.drop_index(op.f('ix_co_templates_id'), table_name='co_templates')
    op.drop_table('co_templates')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_student_info_id'), table_name='student_info')
    op.drop_table('student_info')
    # ### end Alembic commands ###
